#include txt.yml

eval_train_epoch_fraction: arange(.5, .8, .9)

model:
  dropout_p: .1           # N/A
  projection_hidden: 800  # N/A

  projector: simple
  projection_size: 64, 512, 256
  backbone_network: "distilbert-base-uncased"

dataset:
  max_classes: 5

  input_position: 1
  label_position: 0
  
  ood_input_position: 0
  ood_label_position: 1

  train_dataset: 
    name: scientific_papers
    task: arxiv
    root: ./dataset
  ood_detection_dataset: 
    name: rotten_tomatoes
    root: ./dataset

