#include txt.yml

eval_train_epoch_fraction: arange(2., 5.)

model:
  dropout_p: .1           # N/A
  projection_hidden: 800  # N/A

  projector: identity
  projection_size: 64, 512, 256
  backbone_network: '"roberta-base", "albert-base-v2", "bert-base-uncased", "distilbert-base-uncased"'

dataset:
  max_classes: 5

  input_position: 0
  label_position: 1
  
  ood_input_position: 0
  ood_label_position: 1

  train_dataset: 
    name: tweet_eval
    task: '"emotion", "hate", "irony"'
    root: ./dataset
  ood_detection_dataset: 
    name: emotion
    root: ./dataset

