#include txt.yml

lambda_c: 2.

dataset:
  max_classes: 5

  input_position: 1
  label_position: 0
  
  ood_input_position: 1
  ood_label_position: 0

  train_dataset: 
    name: AG_NEWS
    root: ./dataset/AG_NEWS
  ood_detection_dataset: 
    name: newspop
    root: ./dataset/newspop  