debug: False
seed: 43 # seed for reproductibility
epochs: 10
clip: 1.
data_type: txt

force_make_table_dataset: True
text_shift_stength: .1

# CIDER params
temp: .3
alpha: .98 # 1: anchors wont change
lambda_c: .1
lambda_d: .2

freeze_backbone: False
eval_train_epoch_fraction: .5

# Step2 params
samples: 8
noise_samples: 10
tokenizer_max_length: 128 # sequence length
task: tbd

method: baye_by_backprop

model:
  backbone_network: distilbert-base-uncased
  projection_hidden: 800 #10_152
  projection_size: 256 #5_576
  dropout_p: .2


loader:
  num_workers: 0
  batch_size: 16
  pin_memory: true
  drop_last: true

optim:
  name: adamw
  lr: 1e-4

env:
  fp16: false
  n_gpu: 1
  distributed: False

scheduler:
  name: cycle
  decay: lin, cos
  n_iter: 18_750