debug: False
seed: 43 # seed for reproductibility
epochs: 1
clip: 1.
data_type: img

force_make_table_dataset: True
text_shift_stength: .1

# CIDER params
temp: .3
alpha: .95 # 1: anchors wont change
lambda_c: 1.
lambda_d: 1.5

freeze_backbone: False
eval_train_epoch_fraction: .5

# Step2 params
samples: 8
noise_samples: 10
tokenizer_max_length: 128 # sequence length
task: tbd
method: baye_by_backprop


eval_train_epoch_fraction: arange(.1, .5, .1)

model:
  output_features: 151296
  dropout_p: .1           # N/A
  projection_hidden: 800  # N/A

  projector: simple
  projection_size: 64, 512, 256
  backbone_network: google/vit-base-patch16-224-in21k #"microsoft/beit-base-patch16-224" # '"vgg16", "resnet18", 

dataset:
  max_classes: 10

  input_position: 0
  label_position: 1
  
  ood_input_position: 0
  ood_label_position: 1

  target_size: [224, 224]

  train_dataset: 
    name: cifar10
    root: ./dataset
  ood_detection_dataset: 
    name: cifar100
    root: ./dataset

loader:
  num_workers: 0
  batch_size: 32
  pin_memory: false
  drop_last: true

optim:
  name: adamw
  lr: 1e-4

env:
  fp16: false
  n_gpu: 1
  distributed: False

scheduler:
  name: cycle
  decay: lin, cos
  n_iter: 18_750