debug: True
epochs: 10
clip: 1
data_type: txt


# CIDER params
text_shift_stength: .5
temp: .1
alpha: .95 # 1: anchors wont change
lambda_c: 1.
lambda_d: 2.

freeze_backbone: False
samples: 8
noise_samples: 10
tokenizer_max_length: 128 # sequence length
task: tbd

method: baye_by_backprop

model:
  backbone_network: distilbert-base-uncased
  projection_size: 712
  projection_hidden: 712
  dropout_p: .2

dataset:
  max_classes: 4
  train_dataset: 
    name: AG_NEWS
    root: ./dataset/train
  ood_detection_dataset: 
    name: EnWik9

loader:
  num_workers: 0
  batch_size: 8
  pin_memory: false
  drop_last: true

optim:
  name: adamw
  lr: 1e-7

env:
  fp16: false
  n_gpu: 1
  distributed: False

scheduler:
  name: cycle
  decay: lin, cos
  n_iter: 10_000