debug: False
epochs: 1
clip: 1

freeze_backbone: False
samples: 8
noise_samples: 10
tokenizer_max_length: 120 # sequence length
task: tbd

method: baye_by_backprop

model:
  backbone_network: distilbert-base-uncased
  projection_size: 200
  projection_hidden: 200
  dropout_p: .1

dataset:
  train_dataset: 
    name: AG_NEWS
    root: ./dataset/train
  ood_detection_dataset: 
    name: EnWik9

loader:
  num_workers: 0
  batch_size: 16
  pin_memory: false
  drop_last: true

optim:
  name: adamw
  lr: 1e-3

env:
  fp16: false
  n_gpu: 1
  distributed: False

scheduler:
  name: cycle
  decay: lin, cos
  n_iter: 10_000