debug: False
seed: 43
epochs: 20
clip: 1
data_type: img
force_make_table_dataset: False

# CIDER params
text_shift_stength: -1 # doesnt matter here
temp: .1
alpha: .95
lambda_c: 1.
lambda_d: 10.

# Plus tard
freeze_backbone: False
samples: 8
noise_samples: 10
tokenizer_max_length: 64 # sequence length
task: tbd
method: baye_by_backprop

model:
  backbone_network: cnn/resnet18
  projection_size: 128
  projection_hidden: 200
  dropout_p: .1

dataset:
  input_features: 3 # b&w pour mnist
  input_position: 0
  label_position: 1 # mnist is (x, y)
  max_classes: 10

  train_dataset: 
    name: CIFAR10
    root: ./dataset/cifar10
  ood_detection_dataset: 
    name: CIFAR100
    root: ./dataset/cifar100

loader:
  num_workers: 0
  batch_size: 32
  pin_memory: false
  drop_last: true

optim:
  name: adamw
  lr: 1e-3

env:
  fp16: false
  n_gpu: 1
  distributed: False

scheduler:
  name: cycle
  decay: lin, cos
  n_iter: 31250