debug: False
seed: 43 # seed for reproductibility
epochs: 10
clip: 1.
data_type: txt

force_make_table_dataset: True
text_shift_stength: .1

# CIDER params
temp: .3
alpha: .95 # 1: anchors wont change
lambda_c: 1.
lambda_d: 1.5

freeze_backbone: False

# Step2 params
samples: 8
noise_samples: 10
tokenizer_max_length: 128 # sequence length
task: tbd

method: baye_by_backprop

model:
  backbone_network: distilbert-base-uncased
  projection_hidden: 10_152
  projection_size: 5_576
  dropout_p: .2

dataset:
  max_classes: 5
  train_dataset: 
    name: AG_NEWS #AG_NEWS
    root: ./dataset/AG_NEWS
  ood_detection_dataset: 
    name: SogouNews
    root: ./dataset/classification  

loader:
  num_workers: 0
  batch_size: 32
  pin_memory: false
  drop_last: true

optim:
  name: adamw
  lr: 1e-4

env:
  fp16: false
  n_gpu: 1
  distributed: False

scheduler:
  name: cycle
  decay: lin, cos
  n_iter: 18_750